          <img src="https://raw.githubusercontent.com/gitUser/gitrepo/output/snake.svg" alt="Snake animation" />

Sbake.yml:
name: Generate snake animation

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule: # executa a cada 12 horas.
    - cron: "* */12 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

  push:
    branches:
    - master
# Regras
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Igorrocha1
          outputs: dist/snake.svg?palette=github-dark


      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
